import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  try {
    const apiKey = process.env.GEMINI_API_KEY?.trim();
    if (!apiKey) {
      return NextResponse.json(
        { error: "GEMINI_API_KEY environment variable is missing." },
        { status: 500 }
      );
    }

    const { query } = await req.json();
    if (!query || typeof query !== "string") {
      return NextResponse.json({ error: "Input query is required" }, { status: 400 });
    }

    const systemPrompt = `You are a bilingual authority on Haridasa Sahitya and Kannada linguistics.
Analyze the user's input (Kannada script or English/Kanglish phonetics) and return a strictly valid JSON object matching this structure:
{
  "titleKannada": "Title in Kannada script",
  "titleEnglish": "Title in English/IAST",
  "composerKannada": "Composer in Kannada",
  "composerEnglish": "Composer in English",
  "ankitaKannada": "Mudra in Kannada",
  "ankitaEnglish": "Mudra in English",
  "anvayaKannada": "Syntactic rearrangement in modern spoken Kannada sentence order",
  "anvayaEnglish": "Prose translation and flow in clear modern English",
  "pratipadaartha": [
    {
      "wordKannada": "Word",
      "wordTransliterated": "Transliteration",
      "meaningKannada": "Meaning in modern Kannada",
      "meaningEnglish": "Meaning in English"
    }
  ],
  "metaphorsAndMundige": [
    {
      "motifKannada": "Motif in Kannada",
      "motifEnglish": "Motif in English",
      "innerMeaningKannada": "Allegorical meaning in Kannada",
      "innerMeaningEnglish": "Allegorical meaning in English"
    }
  ],
  "modernTakeawayKannada": "1-sentence life takeaway in Kannada",
  "modernTakeawayEnglish": "1-sentence life takeaway in English",
  "youtubeSearchQuery": "Song Title Composer rendition"
}`;

    // Target the current flash model directly via REST
    const modelEndpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${apiKey}`;

    const res = await fetch(modelEndpoint, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: `${systemPrompt}\n\nAnalyze this Haridasa composition:\n"""\n${query}\n"""`
              }
            ]
          }
        ],
        generationConfig: {
          responseMimeType: "application/json",
          temperature: 0.2
        }
      })
    });

    const data = await res.json();

    if (!res.ok) {
      console.error("Google API REST Error:", JSON.stringify(data));
      return NextResponse.json(
        { error: data.error?.message || `Google API returned status ${res.status}` },
        { status: res.status }
      );
    }

    const rawText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!rawText) {
      return NextResponse.json({ error: "No response text generated by model" }, { status: 500 });
    }

    const cleanJson = rawText.replace(/```json/g, "").replace(/```/g, "").trim();
    const parsed = JSON.parse(cleanJson);

    return NextResponse.json(parsed);
  } catch (error: any) {
    console.error("Server Route Error:", error);
    return NextResponse.json({ error: error?.message || "Internal server error" }, { status: 500 });
  }
}
